
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://siqbckcqpajnlvygpdjp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNpcWJja2NxcGFqbmx2eWdwZGpwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcyMDc2NjAsImV4cCI6MjA2Mjc4MzY2MH0.tf5FhiXa2qzBqwTZ7loQwmaEHi06kAIB85BZU_z4CEk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
